name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt huggingface_hub

    # Step 4: Deploy to Hugging Face Spaces using Python API
    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python - <<EOF
        from huggingface_hub import HfApi
        api = HfApi()
        api.upload_folder(
            folder_path=".",
            path_in_repo=".",
            repo_id="Kashuf/demo2",
            repo_type="space",
            token="${{ secrets.HF_TOKEN }}"
        )
        EOF
